BEGIN;

CREATE TABLE USERS (
				ID SERIAL PRIMARY KEY,
				PROVIDER VARCHAR(255),
				USERID VARCHAR(255),
				NAME VARCHAR(255),
				NICKNAME VARCHAR(255),
				EMAIL VARCHAR(255) UNIQUE,
				LOCATION VARCHAR(255),
				DESCRIPTION TEXT,
				ACCESSTOKEN TEXT,
				REFRESHTOKEN TEXT,
				EXPIRESAT TIMESTAMPTZ,
				PICTURELINK VARCHAR(255),
				CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
				UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_USERS_EMAIL ON USERS (EMAIL);
CREATE INDEX IDX_USERS_PROVIDER_USERID ON USERS (PROVIDER, USERID);

COMMIT;
